/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Product = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdBy' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Opt(IDL.Text),
  'phoneNumber' : IDL.Opt(IDL.Text),
});
export const OrderResponse = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'createdBy' : IDL.Principal,
  'totalAmount' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : IDL.Int,
  'items' : IDL.Vec(CartItem),
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGuestOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(CartItem)],
      [IDL.Nat],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(CartItem)],
      [IDL.Nat],
      [],
    ),
  'createProduct' : IDL.Func([Product], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(OrderResponse)], ['query']),
  'getProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateProductPrices' : IDL.Func(
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'upsertProductsAdmin' : IDL.Func([IDL.Vec(Product)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Product = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdBy' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Opt(IDL.Text),
    'phoneNumber' : IDL.Opt(IDL.Text),
  });
  const OrderResponse = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'createdBy' : IDL.Principal,
    'totalAmount' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : IDL.Int,
    'items' : IDL.Vec(CartItem),
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGuestOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(CartItem)],
        [IDL.Nat],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Vec(CartItem)],
        [IDL.Nat],
        [],
      ),
    'createProduct' : IDL.Func([Product], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [IDL.Opt(OrderResponse)], ['query']),
    'getProductsAdmin' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateProductPrices' : IDL.Func(
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        [],
        [],
      ),
    'upsertProductsAdmin' : IDL.Func([IDL.Vec(Product)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };